### ISSUE TITLE
Stuck at boot screen

### ISSUE THREAD

**Issue by mujtaba617** [d4vinder/HP-zBookPro-G1-macOS-Catalina#4]
When I try booting from Clover, can't get past apple logo screen. It just restarts from there.

My configuration:
Zbook 15g1
Adata 256 gb SSD
i7 4900 MQ 3.6 Ghz
8 gb DDR3 ram

**Comment by mujtaba617** [comment]
Please help! 😢

**Comment by d4vinder** [comment]
Add the flags -v and Dart=0 to your boot option in clover. start there. Also ensure your BIOS is set correctly.

**Comment by mujtaba617** [comment]
![IMG_20200705_150217_LL](https://user-images.githubusercontent.com/26211405/86530265-b8230800-bed0-11ea-9a0a-b81f7f24f0f7.jpg)

**Comment by mujtaba617** [comment]
I did. Here are the results:'

**```
AMF: Only 248/266 slide values are usable!
Valid slides: 8-255

Invalid device tree for kext injection
```**

**Comment by d4vinder** [comment]
What is your hardware spec?

**Comment by mujtaba617** [comment]
Zbook 15g1

Adata SU800 256 gb SSD

Seagate ST500 500 gb HDD

i7 4900 MQ 2.8ghz

8 gb DDR3 ram

**Comment by mujtaba617** [comment]
Can you drop a hint on how to fix it?

**Comment by d4vinder** [comment]
Try the original guide https://www.tonymacx86.com/threads/guide-hp-probook-elitebook-zbook-using-clover-uefi-hotpatch.261719/

Also ensure you’re using UEFI boot.
