### ISSUE TITLE
Big Sur support

### ISSUE THREAD

**Issue by Thatisjigen** [d4vinder/HP-zBookPro-G1-macOS-Catalina#6]
Hi, clover isn't supporting Big Sur, atleast not the version you have posted, is there any plan to switch to OC or updating clover to the one supporting 11?

**Comment by d4vinder** [comment]
> Hi, clover isn't supporting Big Sur, atleast not the version you have posted, is there any plan to switch to OC or updating clover to the one supporting 11?

No plans to upgrade to bigsur just yet.
